# Generated by Django 5.1.4 on 2024-12-20 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию",
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Фамилия должна содержать только русские буквы",
                                regex="^[а-яА-ЯёЁ\\s-]+$",
                            )
                        ],
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "team_number",
                    models.IntegerField(
                        help_text="Введите номер бригады",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Номер бригады",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Введите зарплату",
                        max_digits=10,
                        verbose_name="Зарплата",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("Прораб", "Прораб"),
                            ("Бригадир", "Бригадир"),
                            ("Чистовая отделка", "Чистовая отделка"),
                            ("Черновая отделка", "Черновая отделка"),
                        ],
                        default="Черновая отделка",
                        help_text="Выберите специализацию",
                        max_length=50,
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работник",
                "verbose_name_plural": "Работники",
                "ordering": ["last_name"],
            },
        ),
    ]
